name: Python Package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: .
        strategy:
            matrix:
                python-version: [3.5, 3.7, 3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Get current working directory
          run: |
            export PYTHONPATH=${{ env.working-directory }}
            echo $PYTHONPATH
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with flake8
          run: |
            # Stop the build if there are Python sintax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # Exit-zero treats all errors as warnings
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Test with pytest
          run: |
            pytest src/python/
